/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginSignup;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import personalfinancemanagementsystem.DBA;
import personalfinancemanagementsystem.DBK;

/**
 *
 * @author RaFiveSRD
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teksSIGNUP = new javax.swing.JLabel();
        teksN = new javax.swing.JLabel();
        kotakN = new javax.swing.JTextField();
        teksUSN = new javax.swing.JLabel();
        kotakUSN = new javax.swing.JTextField();
        teksPW = new javax.swing.JLabel();
        kotakPW = new javax.swing.JPasswordField();
        teksKPW = new javax.swing.JLabel();
        kotakKPW = new javax.swing.JPasswordField();
        tombolMendaftar = new javax.swing.JButton();
        teksMasuklah = new javax.swing.JLabel();
        tombolLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/BG02.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        teksSIGNUP.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        teksSIGNUP.setForeground(new java.awt.Color(0, 153, 255));
        teksSIGNUP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teksSIGNUP.setText("SIGN UP");

        teksN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        teksN.setText("Nama");

        kotakN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotakNActionPerformed(evt);
            }
        });

        teksUSN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        teksUSN.setText("Username");

        teksPW.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        teksPW.setText("Password");

        kotakPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotakPWActionPerformed(evt);
            }
        });

        teksKPW.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        teksKPW.setText("Konfirmasi Password");

        kotakKPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotakKPWActionPerformed(evt);
            }
        });

        tombolMendaftar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tombolMendaftar.setText("Buat Akun");
        tombolMendaftar.setToolTipText("");
        tombolMendaftar.setPreferredSize(new java.awt.Dimension(105, 35));
        tombolMendaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolMendaftarActionPerformed(evt);
            }
        });

        teksMasuklah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teksMasuklah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teksMasuklah.setText("Sudah Punya Akun? Login Untuk Masuk");

        tombolLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tombolLogin.setText("Login");
        tombolLogin.setPreferredSize(new java.awt.Dimension(80, 35));
        tombolLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(teksSIGNUP, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tombolMendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teksKPW, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teksPW, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teksN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kotakN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teksUSN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kotakUSN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kotakPW, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kotakKPW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(teksMasuklah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tombolLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                                .addGap(20, 20, 20)))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(teksSIGNUP)
                .addGap(18, 18, 18)
                .addComponent(teksN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotakN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teksUSN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotakUSN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teksPW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotakPW, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teksKPW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotakKPW, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolMendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(teksMasuklah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kotakKPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotakKPWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotakKPWActionPerformed

    private void tombolLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLoginActionPerformed
        Login keLogin = new Login();
        keLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolLoginActionPerformed

    private void tombolMendaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolMendaftarActionPerformed
        String nama = kotakN.getText().trim();
        String username = kotakUSN.getText().trim();
        String password = new String(kotakPW.getPassword());
        String konfirmasi = new String(kotakKPW.getPassword());

        if (nama.isEmpty() || username.isEmpty() || password.isEmpty() || konfirmasi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua Kolom Harus Terisi!", "ALERT", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (password.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password Minimal 8 Karakter!", "ALERT", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(null, "Password Tidak Cocok!", "ALERT", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = DBA.DBACC()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(null, "Koneksi Database Gagal!");
                return;
            }

            String cekSQL = "SELECT * FROM Akun WHERE usernameACC = ?";
            try (PreparedStatement cek = conn.prepareStatement(cekSQL)) {
                cek.setString(1, username);
                try (ResultSet rs = cek.executeQuery()) {
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Username Sudah Terdaftar! Gunakan Username Lain", "ALERT", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }

            String sql = "INSERT INTO Akun (namaACC, usernameACC, passwordACC) VALUES (?, ?, ?)";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, nama);
                ps.setString(2, username);
                ps.setString(3, password);
                ps.executeUpdate();
            }

            String userDbPath = "C:\\Users\\RaFiveSRD\\Documents\\NetBeansProjects\\PersonalFinanceManagementSystem\\DataBase\\" + "Finance_" + username + ".db";
            DBK.createNewUserDatabase(userDbPath);

            JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat! Silahkan Login", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            Login keLogin = new Login();
            keLogin.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Database: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tombolMendaftarActionPerformed

    private void kotakNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotakNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotakNActionPerformed

    private void kotakPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotakPWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotakPWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField kotakKPW;
    private javax.swing.JTextField kotakN;
    private javax.swing.JPasswordField kotakPW;
    private javax.swing.JTextField kotakUSN;
    private javax.swing.JLabel teksKPW;
    private javax.swing.JLabel teksMasuklah;
    private javax.swing.JLabel teksN;
    private javax.swing.JLabel teksPW;
    private javax.swing.JLabel teksSIGNUP;
    private javax.swing.JLabel teksUSN;
    private javax.swing.JButton tombolLogin;
    private javax.swing.JButton tombolMendaftar;
    // End of variables declaration//GEN-END:variables
}
